# Service account of env-checker, that will be bound with cluster role
serviceAccount:
  name: env-checker-sa
  # Enable mounting service account token for kubectl access
  automountToken: true

# kubernetes secret name. Only pods which provide own keys can access the private registry.
imagePullSecrets: []

# Defines microservice name
SERVICE_NAME: "env-checker"
APPLICATION_NAME: "env-checker"
MANAGED_BY: "saasDeployer"
# The namespace it is going to be deployed.
NAMESPACE: 'default'
# Artifact descriptor version which is installed.
ARTIFACT_DESCRIPTOR_VERSION: ''
# IMAGE_REPOSITORY: 'ghcr.io/netcracker/qubership-env-checker'
# TAG: 'main'
DELIMITER: "-"
DEPLOYMENT_SESSION_ID: ''
CLOUD_NAME: 'qubership'
CSE_CLOUD: ''
CSE_TENANT: ''
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false
# Jupyter lab access token value
# ENVIRONMENT_CHECKER_UI_ACCESS_TOKEN: ''

# Specific env-check variables
ENVIRONMENT_CHECKER_JOB_COMMAND: ''
ENVIRONMENT_CHECKER_CRON_JOB_COMMAND: ''
ENVIRONMENT_CHECKER_CRON_SCHEDULE: '0 0 */12 * *'
# Parameters related to oauth proxy
OPS_IDP_URL: ''
ENVCHECKER_KEYCLOACK_REALM: ''
ENVCHECKER_KEYCLOACK_CLIENT_ID: ''
ENVCHECKER_KEYCLOACK_CLIENT_SECRET: ''
CLOUD_PUBLIC_HOST: 'qubership'

PRODUCTION_MODE: FALSE
ENVIRONMENT_CHECKER_LOG_LEVEL: 'ERROR'
ENVCHECKER_STORAGE_BUCKET: 'storage-env-checker'
ENVIRONMENT_CHECKER_STORAGE_BUCKET_EXPIRATION_DAYS: 14

MONITORING_PASSWORD: ''
MONITORING_USER: ''
MONITORING_URL: ''

STORAGE_SERVER_URL: ''
STORAGE_PROVIDER: ''
STORAGE_USERNAME: ''
STORAGE_PASSWORD: ''
STORAGE_REGION: ''

# Git username, token and domain for legacy git_helper.sh.
ENVCHECKER_GIT_USERNAME: ''
ENVCHECKER_GIT_TOKEN: ''
# If empty, will be extracted from repositoryUrl.
ENVCHECKER_GIT_DOMAIN: ''

git:
  # Username for accessing a private GIT repository. Used for authentication.
  username: ''
  # Personal Access Token for a private GIT repository. Used for authentication.
  token: ''
  # URL of the GIT repository to fetch files/notebooks from.
  repositoryUrl: ''
  # Path in the container where fetched files/notebooks will be placed.
  targetPath: ''
  # Path or pattern for sparse checkout â€” which files/folders to fetch from the repository.
  sparsePath: ''
  # Branch of the GIT repository to fetch files from.
  branch: 'main'
